import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowUpRight, ShieldCheck, LogOut, RefreshCw, Plus, X, Check, Database, FileSearch, ListTodo, LoaderCircle, ChevronRight, Settings2 } from 'lucide-react';
import { api, statusLabel } from './api';
import { Brand } from './App';

const blankSource = { name: '', type: 'river', format: 'arcgis', url: '', nameField: 'name', idField: 'OBJECTID', licence: '', attribution: '', version: '', completeness: 'unknown', aliases: [] as string[], notes: '', status: 'pending' };
const date = (s: string) => new Date(s).toLocaleString();
export function Admin() {
  const [session, setSession] = useState<any>(null), [password, setPassword] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [data, setData] = useState<any>(null), [tab, setTab] = useState('jobs'), [editing, setEditing] = useState<any>(null), [report, setReport] = useState<any>(null), [notes, setNotes] = useState('');
  const [featureSettings, setFeatureSettings] = useState<any>(null), [aliases, setAliases] = useState('');
  const refresh = () => api('/admin/overview').then(setData).catch(e => setError(e.message));
  useEffect(() => { api('/admin/session').then(setSession).catch(e => setError(e.message)); }, []);
  useEffect(() => { if (!session?.authenticated) return; refresh(); const timer = setInterval(refresh, 3000); return () => clearInterval(timer); }, [session?.authenticated]);
  async function action(fn: () => Promise<unknown>) { setError(''); setBusy(true); try { await fn(); await refresh(); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function login(e: React.FormEvent) { e.preventDefault(); setError(''); setBusy(true); try { await api(`/admin/${session.setupRequired ? 'setup' : 'login'}`, 'POST', { password }); setPassword(''); setSession(await api('/admin/session')); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function saveSource(status: string) {
    await action(async () => { const body = { ...editing, status }; if (editing.id) await api(`/admin/sources/${editing.id}`, 'PATCH', body); else { const added = await api('/admin/sources', 'POST', body); if (status !== 'pending') await api(`/admin/sources/${added.id}`, 'PATCH', body); } setEditing(null); });
  }
  const needsReview = (r: any) => r.status === 'pending' && data.jobs.find((j: any) => j.id === r.job_id)?.phase === 'awaiting_review' && data.reports.find((other: any) => other.job_id === r.job_id)?.id === r.id;
  const pending = data?.reports.filter(needsReview).length || 0;
  const active = (job: any) => ['queued', 'importing', 'processing', 'researching'].includes(job.phase);
  const selectedFeatures = featureSettings ? data?.features.filter((f: any) => f.id === featureSettings.feature_id || featureSettings.matches?.some((m: any) => m.id === f.id)) || [] : [];
  const suggestedAliases: string[] = featureSettings ? [...new Set<string>((data?.reports || []).filter((r: any) => r.job_id === featureSettings.id && r.status !== 'rejected').flatMap((r: any) => (r.data.candidates || []).flatMap((c: any) => c.aliases || [])))] : [];
  return <div className="admin-shell">
    <header className="topbar"><Brand/><span className="workspace-label">ADMINISTRATION</span><a className="admin-link" href="/"><ArrowLeft size={16}/>Back to map</a>{session?.authenticated && <button className="icon-button" title="Sign out" aria-label="Sign out" onClick={async () => { await api('/admin/logout', 'POST', {}); setSession({ ...session, authenticated: false }); }}><LogOut size={18}/></button>}</header>
    {!session ? <div className="page-loading"><LoaderCircle className="spin"/>Loading administration{error && <p className="error">{error}</p>}</div> : !session.authenticated ? <main className="login-page"><div className="login-mark"><ShieldCheck size={32}/></div><span className="eyebrow">GEOXPL WORKSPACE</span><h1>{session.setupRequired ? 'Set up administration' : 'Administrator sign-in'}</h1><p className="muted">{session.setupRequired ? 'Create the password for this local workspace.' : 'Review sources, research, and processing.'}</p><form onSubmit={login}><label>Password<input aria-label="Administrator password" type="password" autoComplete={session.setupRequired ? 'new-password' : 'current-password'} value={password} onChange={e => setPassword(e.target.value)} minLength={session.setupRequired ? 12 : 1} maxLength={200} required autoFocus/></label>{session.setupRequired && <small className="muted">At least 12 characters.</small>}{error && <p className="error" role="alert">{error}</p>}<button className="primary full" disabled={busy || (session.setupRequired && !session.localSetup)}>{busy && <LoaderCircle className="spin" size={16}/>} {session.setupRequired ? 'Create administrator' : 'Sign in'}<ChevronRight size={17}/></button>{session.setupRequired && !session.localSetup && <p className="warning">Run npm run admin:password on the server to create an administrator.</p>}</form></main> : <main className="admin-main">
      <div className="admin-heading"><div><span className="eyebrow">WORKSPACE</span><h1>Processing & sources</h1></div><button className="secondary" onClick={refresh}><RefreshCw size={16}/>Refresh</button></div>
      {error && <p className="error" role="alert">{error}<button aria-label="Dismiss error" onClick={() => setError('')}><X size={16}/></button></p>}
      {data && <><div className="metrics"><div><span>Searches</span><strong>{data.searches}</strong></div><div><span>Resolved</span><strong>{data.jobs.filter((j: any) => j.status === 'resolved').length}</strong></div><div><span>Awaiting review</span><strong>{pending}</strong></div><div><span>Approved sources</span><strong>{data.sources.filter((s: any) => s.status === 'approved').length}</strong></div><div><span>AI research</span><strong className="metric-text">{data.aiConfigured ? 'Configured' : 'Not configured'}</strong><small>{data.aiHourlyLimit} requests / hour limit</small></div></div>
      <div className="admin-tabs"><button className={tab === 'jobs' ? 'active' : ''} onClick={() => setTab('jobs')}><ListTodo size={17}/>Requests</button><button className={tab === 'sources' ? 'active' : ''} onClick={() => setTab('sources')}><Database size={17}/>Source registry</button><button className={tab === 'reports' ? 'active' : ''} onClick={() => setTab('reports')}><FileSearch size={17}/>Research {pending > 0 && <span className="nav-count">{pending}</span>}</button><button className={tab === 'activity' ? 'active' : ''} onClick={() => setTab('activity')}>Activity</button></div>
      {tab === 'jobs' && <><div className="section-heading"><h2>Feature requests</h2><span className="muted small">{data.jobs.length} requests</span></div><div className="table-wrap"><table><thead><tr><th>Feature</th><th>Outcome</th><th>Processing stage</th><th>Updated</th><th/></tr></thead><tbody>{data.jobs.map((j: any) => <tr key={j.id}><td><strong>{j.query}</strong><small>{j.type}</small></td><td><span className={`badge ${j.status === 'resolved' ? 'green' : ''}`}>{statusLabel(j.status)}</span></td><td>{statusLabel(j.phase)}</td><td>{date(j.updated)}</td><td><div className="request-actions"><button className="icon-button" title="Feature settings" aria-label={`Feature settings for ${j.query}`} disabled={busy || active(j)} onClick={() => { setFeatureSettings({ ...j, ...j.settings }); setAliases((j.settings.aliases || []).join('\n')); }}><Settings2 size={17}/></button><button className="secondary small-button" disabled={busy || active(j)} onClick={() => action(() => api(`/admin/jobs/${j.id}/retry`, 'POST', {}))}><RefreshCw size={14}/>Retry</button><button className="icon-button" title="New AI research (may incur API charges)" aria-label={`New research for ${j.query}`} disabled={busy || active(j)} onClick={() => { if (window.confirm('Request fresh AI research? API charges may apply.')) action(() => api(`/admin/jobs/${j.id}/research`, 'POST', {})); }}><FileSearch size={17}/></button></div></td></tr>)}</tbody></table></div>{!data.jobs.length && <div className="empty-state"><ListTodo size={30}/><h2>No requests yet</h2><p>Search for a river or valley from the map.</p></div>}</>}
      {tab === 'sources' && <><div className="section-heading"><h2>Data sources</h2><button className="primary" onClick={() => setEditing({ ...blankSource })}><Plus size={16}/>Add source</button></div><div className="table-wrap"><table><thead><tr><th>Dataset</th><th>Type / format</th><th>Status</th><th>Coverage</th><th/></tr></thead><tbody>{data.sources.map((s: any) => <tr key={s.id}><td><strong>{s.name}</strong><small className="truncate-url">{s.url}</small></td><td>{s.type}<small>{s.format}</small></td><td><span className={`badge ${s.status === 'approved' ? 'green' : s.status === 'pending' ? 'amber' : ''}`}>{statusLabel(s.status)}</span></td><td>{s.completeness}</td><td><button className="secondary small-button" onClick={() => setEditing({ ...s })}>Review<ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div>{!data.sources.length && <div className="empty-state"><Database size={30}/><h2>No sources registered</h2><p>Research recommendations and manually added sources appear here.</p></div>}</>}
      {tab === 'reports' && <><div className="section-heading"><h2>Research reports</h2><span className="muted small">{pending} awaiting review</span></div><div className="report-list">{data.reports.map((r: any) => <button key={r.id} onClick={() => { setReport(r); setNotes(r.data.adminNotes || ''); }}><FileSearch size={22}/><span><strong>{data.jobs.find((j: any) => j.id === r.job_id)?.query || 'Research'}</strong><small>{r.data.summary}</small><span className="report-meta">{r.data.provider} · {date(r.created)}</span></span><span className={`badge ${needsReview(r) ? 'amber' : ''}`}>{r.status === 'pending' && !needsReview(r) ? 'Historical' : statusLabel(r.status)}</span><ChevronRight size={18}/></button>)}</div>{!data.reports.length && <div className="empty-state"><FileSearch size={30}/><h2>No research reports</h2><p>Unresolved requests produce recommendations here.</p></div>}</>}
      {tab === 'activity' && <><div className="section-heading"><h2>Processing activity</h2><span className="small muted">Latest 100 events</span></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Event</th><th>Detail</th></tr></thead><tbody>{data.events.map((e: any) => <tr key={e.id}><td>{date(e.created)}</td><td>{statusLabel(e.action)}</td><td>{e.detail}</td></tr>)}</tbody></table></div></>}
      </>}
    </main>}
    {featureSettings && <div className="modal-backdrop" onClick={() => !busy && setFeatureSettings(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="feature-settings-title" onClick={e => e.stopPropagation()}><header><h2 id="feature-settings-title">{featureSettings.query}</h2><button className="icon-button" aria-label="Close feature settings" onClick={() => setFeatureSettings(null)}><X size={20}/></button></header><form onSubmit={e => { e.preventDefault(); action(async () => { await api(`/admin/jobs/${featureSettings.id}/settings`, 'PATCH', { aliases: aliases.split('\n').map(s => s.trim()).filter(Boolean), preferredSourceId: featureSettings.preferredSourceId || null }); setFeatureSettings(null); }); }}>
      <div className="form-grid"><label className="span-two">Approved feature aliases<textarea aria-label="Approved feature aliases" title="One approved alias per line" rows={3} value={aliases} onChange={e => setAliases(e.target.value)}/></label>
      {suggestedAliases.length > 0 && <div className="span-two alias-suggestions">{suggestedAliases.filter(a => !aliases.toLowerCase().split('\n').includes(a.toLowerCase())).map(a => <button type="button" className="text-button" key={a} title={`Add suggested alias ${a}`} onClick={() => setAliases(current => [current, a].filter(Boolean).join('\n'))}><Plus size={14}/>{a}</button>)}</div>}
      <label className="span-two">Geometry source<select aria-label="Geometry source" value={featureSettings.preferredSourceId || ''} onChange={e => setFeatureSettings({ ...featureSettings, preferredSourceId: e.target.value || null })}><option value="">Automatic (identity, quality and coverage)</option>{featureSettings.preferredSourceId && !data.sources.some((s: any) => s.id === featureSettings.preferredSourceId && s.status === 'approved') && <option value={featureSettings.preferredSourceId} disabled>Previously selected source (not approved)</option>}{data.sources.filter((s: any) => s.status === 'approved' && s.type === featureSettings.type).map((s: any) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div>
      {selectedFeatures.map((selectedFeature: any) => <div className="feature-diagnostics" key={selectedFeature.id}><h3>{selectedFeature.displayName || selectedFeature.name}</h3><span className="badge">{statusLabel(selectedFeature.status)}</span>{selectedFeature.warnings.map((warning: string, index: number) => <p className="warning" key={index}>{warning}</p>)}<div className="table-wrap"><table><thead><tr><th>Dataset</th><th>Records</th><th>Excluded</th><th>Components</th></tr></thead><tbody>{selectedFeature.selection?.comparisons.map((c: any, index: number) => <tr key={`${c.sourceId}:${c.identityKey || index}`}><td>{c.sourceName}{c.identityKey && <small>{c.identityKey}</small>}{c.sourceId === selectedFeature.selection.sourceId && <small>Selected</small>}{c.error && <small>{c.error}</small>}</td><td>{c.records ?? '-'}</td><td>{c.excludedRecords ?? '-'}</td><td>{c.components ?? '-'}</td></tr>)}</tbody></table></div></div>)}
      {error && <p className="error" role="alert">{error}</p>}<footer className="modal-actions"><button type="button" className="secondary" onClick={() => setFeatureSettings(null)}>Cancel</button><button className="primary" disabled={busy}><Check size={16}/>Save & retry</button></footer></form></section></div>}
    {editing && <div className="modal-backdrop" onClick={() => !busy && setEditing(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="source-title" onClick={e => e.stopPropagation()}><header><h2 id="source-title">{editing.id ? 'Review source' : 'Register source'}</h2><button className="icon-button" aria-label="Close source" onClick={() => setEditing(null)}><X size={20}/></button></header><form onSubmit={e => { e.preventDefault(); saveSource('approved'); }}>
      <div className="form-grid"><label className="span-two">Dataset name<input required value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })}/></label><label>Feature type<select value={editing.type} onChange={e => setEditing({ ...editing, type: e.target.value })}><option value="river">River</option><option value="valley">Valley</option></select></label><label>Format<select value={editing.format} onChange={e => setEditing({ ...editing, format: e.target.value })}><option value="arcgis">ArcGIS layer</option><option value="geojson">GeoJSON collection</option></select></label><label className="span-two">Data endpoint (HTTPS)<input type="url" required value={editing.url} onChange={e => setEditing({ ...editing, url: e.target.value })}/></label><label>Name field<input required value={editing.nameField} onChange={e => setEditing({ ...editing, nameField: e.target.value })}/></label><label>Object ID field<input required value={editing.idField} onChange={e => setEditing({ ...editing, idField: e.target.value })}/></label><label>Verified licence<input required value={editing.licence} onChange={e => setEditing({ ...editing, licence: e.target.value })}/></label><label>Attribution<input required value={editing.attribution} onChange={e => setEditing({ ...editing, attribution: e.target.value })}/></label><label>Source version<input value={editing.version} onChange={e => setEditing({ ...editing, version: e.target.value })}/></label><label>Named-feature coverage<select value={editing.completeness} onChange={e => setEditing({ ...editing, completeness: e.target.value })}><option value="unknown">Unknown</option><option value="partial">Partial / regional</option><option value="complete">Complete named features</option></select></label><label className="span-two">Review notes<textarea rows={3} value={editing.notes} onChange={e => setEditing({ ...editing, notes: e.target.value })}/></label></div>{error && <p className="error" role="alert">{error}</p>}<footer className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={() => saveSource('rejected')}>Reject</button><button type="button" className="secondary" disabled={busy} onClick={() => saveSource('pending')}>Save pending</button><button className="primary" disabled={busy}><Check size={16}/>Approve & retry</button></footer></form></section></div>}
    {report && <div className="modal-backdrop" onClick={() => !busy && setReport(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="report-title" onClick={e => e.stopPropagation()}><header><h2 id="report-title">Research recommendation</h2><button className="icon-button" aria-label="Close report" onClick={() => setReport(null)}><X size={20}/></button></header><div className="report-body"><span className="eyebrow">{report.data.provider}</span><p>{report.data.summary}</p><h3>Recommended next steps</h3><ol>{report.data.nextSteps?.map((s: string, i: number) => <li key={i}>{s}</li>)}</ol>{report.data.evidence?.map((e: any, i: number) => <a className="source-link" key={i} href={e.url} target="_blank" rel="noreferrer">{e.title}<ArrowUpRight size={16}/></a>)}<label>Administrator notes<textarea rows={4} value={notes} onChange={e => setNotes(e.target.value)}/></label><p className="muted small">Source approval is separate. Only approved sources are used when processing retries.</p>{error && <p className="error" role="alert">{error}</p>}</div><footer className="modal-actions"><button className="secondary" disabled={busy} onClick={() => action(async () => { await api(`/admin/reports/${report.id}`, 'PATCH', { status: 'rejected', notes }); setReport(null); })}>Reject</button><button className="primary" disabled={busy} onClick={() => action(async () => { await api(`/admin/reports/${report.id}`, 'PATCH', { status: 'approved', notes }); setReport(null); })}><Check size={16}/>Mark reviewed</button></footer></section></div>}
  </div>;
}
