export async function api<T = any>(path: string, method = 'GET', body?: unknown, signal?: AbortSignal): Promise<T> {
  const response = await fetch(`/api${path}`, { method, credentials: 'same-origin', signal, headers: { 'Content-Type': 'application/json' }, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`);
  return data;
}
export type NetworkEndpoint = { coordinates: [number, number]; classification: string; nodeId: number; sourceUrl: string; receivingRiver?: string; joiningRiver?: string; namingEvidenceUrl?: string };
export type ExtentEstimate = { kind: 'valley_floor' | 'terrain_valley'; label: string; coverage: 'partial'; scopeNote: string; evidenceUrl: string; sourceScale: string };
export type Interpolation = GeoJSON.Feature<GeoJSON.LineString, { id: string; label: string; kind: string; method: string; certainty: string; lengthKm: number; alternativeGroup?: string; evidenceUrl?: string }>;
export type Feature = { valleyFloor?: { geometry: GeoJSON.Geometry; bbox: [number, number, number, number]; areaKm2: number; extentEstimate: ExtentEstimate }; terrain?: { sensitivity: { intersectionOverUnion: number; scalesMetres: number[]; areaKm2: number[] }; [key: string]: unknown }; extentEstimate?: ExtentEstimate; principalDrainage?: { featureId: string; name: string; checksum: string } | null; interpolations?: GeoJSON.FeatureCollection<GeoJSON.LineString, Interpolation['properties']>; displayBbox?: [number, number, number, number]; interpolationSummary?: { count: number; notes: string[] }; source?: NetworkEndpoint | null; mouth?: NetworkEndpoint | null; mainStem?: { status: string; limitations?: string[] }; recordedNetwork?: { geometry: GeoJSON.Geometry; bbox: [number, number, number, number]; lengthKm: number; recordCount: number }; identity?: unknown; selection?: unknown; id: string; name: string; type: string; geometry: GeoJSON.Geometry; bbox: [number, number, number, number]; status: string; lengthKm: number | null; areaKm2: number | null; confidence: string; method: string; algorithmVersion: string; warnings: string[]; created: string; evidence: { sourceId: string; sourceName: string; sourceUrl: string; licence: string; attribution: string; objectId: string; importId: string; checksum: string; sourceVersion: string }[] };
export type FeatureSummary = Pick<Feature, 'id' | 'name' | 'type' | 'status' | 'lengthKm' | 'areaKm2' | 'bbox'> & { displayName?: string; locationLabel?: string; locationDescription?: string };
export type Job = { id: string; query: string; type: string; status: string; phase: string; message: string; updated: string; feature: Feature | null; selectionRequired?: boolean; matches: FeatureSummary[] };
export const featureLabel = (feature: Feature | FeatureSummary) => (feature as FeatureSummary).displayName || feature.name;
export const statusLabel = (s: string) => ({ pending: 'Pending', resolved: 'Resolved', superseded: 'Superseded', partially_resolved: 'Partially resolved', missing_capability: 'Needs capability', insufficient_data: 'Insufficient data', awaiting_review: 'Awaiting review', awaiting_data: 'Needs geographic evidence', available_estimate: 'Estimate available', queued: 'Queued', processing: 'Processing', failed: 'Failed', approved: 'Approved', rejected: 'Rejected' }[s] || s.replaceAll('_', ' '));
